name = "pierrefouquet-calls"
main = "./worker.js"
compatibility_date = "2025-08-13"

routes = [
  { pattern = "calls.pierrefouquet.co.uk", custom_domain = true }
]

[assets]
directory = "./public"
binding = "ASSETS"

[observability.logs]
enabled = true
