name = "scrncheat-calls"
main = "./worker.js"
compatibility_date = "2025-04-07"
rules = [{type = "Data", globs = ["**/*.html"], fallthrough = true}, {type = "Data", globs = ["**/*.js"]}]

[site]
bucket = "./public"
