name = "scrncheat-calls"
main = "./worker.js"
compatibility_date = "2025-04-07"
rules = [{type = "Data", globs = ["public/index.html"], fallthrough = true}, {type = "Data", globs = ["worker.js"]}]

[site]
bucket = "./public"
