name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@latest
      - name: Deploy
        uses: cloudflare/wrangler-action@latest
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}